prefix content: <http://pkg.samsung.com/content#>
prefix user: <http://pkg.samsung.com/user#>

INSERT {
    ?fourwevent content:attendee ?person .
} WHERE {
    ?fourwevent a content:FourWEvent .
    ?fourwevent content:attendee ?person explicit false .
}

DELETE {
    ?fourwevent content:contactId ?contactId .
} WHERE {
    ?fourwevent a content:FourWEvent .
    ?fourwevent content:contactId ?contactId .
}
