select <OUTPUT>
where{
    {
        select ?content (MAX(?c_time) AS ?content_time) (MAX(?p_score) AS ?pivot_score) (MAX_ARGMAX(?p_class_score, ?p_score) AS ?pivot_class_score)
        where {
            <BODY_SEARCH_PIVOT>
            <CONTENT_FILTER>
            <ONE_HOP_EXPR>
            FILTER EXISTS {?content rdf:type/rdfs:subClassOf content:Content .}
            OPTIONAL {
                ?content time:inXSDCreatedDateTimeStamp|time:inXSDBeginningDateTimeStamp ?c_time .
            }
            <PIVOT_CONNECT>
            <PIVOT_SCORE_SUM>
            <PIVOT_RANK_SCORE>
        }
        GROUP BY ?content
        <SIMPLE_SORT_METHOD>
        <LIMIT>
        <OFFSET_STATEMENT>
    }
    <BODY_GET_TARGET_TRIPLE>
}
<COMPLEX_SORT_METHOD>
