select <OUTPUT>
where{
    {
        select distinct ?person
        where {
            ?person rdf:type/rdfs:subClassOf user:Person .
            FILTER (?person != person:TheUser)
        }
        <SIMPLE_SORT_METHOD>
        <LIMIT>
        <OFFSET_STATEMENT>
    }
    <BODY_GET_TARGET_TRIPLE>
    BIND("UNDEF" AS ?pivot_score)
    BIND("UNDEF" AS ?pivot_class_score)
}
<COMPLEX_SORT_METHOD>

