SELECT DISTINCT ?location (SUM(?duration_sec) / 60 AS ?total_duration_min) (COUNT(?activity) AS ?visits)
WHERE {
    ?activity rdf:type user:Staying .
    ?activity time:hasBeginning/time:inXSDDateTimeStamp ?start_time .
    ?activity time:hasEnd/time:inXSDDateTimeStamp ?end_time .

    ?activity user:atLocation ?location .

    BIND( DURATION_SECONDS (?end_time - ?start_time) AS ?duration_sec)

    <TIME_FILTER>
}
GROUP BY ?location
<OUTPUT_SORT>