SELECT DISTINCT ?location (COUNT(?activity) AS ?visits)
WHERE {
    ?activity rdf:type user:Staying .
    ?activity time:hasBeginning/time:inXSDDateTimeStamp ?start_time .
    ?activity time:hasEnd/time:inXSDDateTimeStamp ?end_time .
    ?activity user:atLocation ?location .
    <LOCATION_FILTER>
    <TIME_FILTER>
}
GROUP BY ?location
<OUTPUT_SORT>