SELECT distinct ?waveNum ?pathNum ?originNode ?bridgeNode ?targetNode ?secondBridgeNode ?score
WHERE {
    VALUES (?originImageFile) {<IMAGE_FILE_IRI>}
        # originNode is  TakingPicturesActivity
        ?originImageFile ^user:objectContent ?originNode.
        {
        SELECT ?waveNum ?pathNum ?originNode ?bridgeNode ?targetNode ?secondBridgeNode ?score
            WHERE{
                VALUES ?waveNum {  4 }
                VALUES ?pathNum { 1 }
                VALUES ?score { 0.5 }
                ?originNode user:atLocation ?bridgeNode.
                BIND(COALESCE(STR(?bridgeNode), "_error_") as ?bridgeNode_iri_string) .
                TT <TUPLE_TABLE_NAME> { ?secondBridgeNode ?bridgeNode_iri_string }
                ?secondBridgeNode ^user:atLocation ?targetNode.
        #        ?bridgeNode ^user:atLocation ?targetNode.
                ?targetNode a user:TakingPictures.
                #FILTER (?originTakingPicturesActivity  != iri)
            }
        }
    }
