SELECT distinct ?waveNum ?pathNum ?originNode ?bridgeNode ?targetNode ?secondBridgeNode ?score
WHERE {
    VALUES (?originImageFile) {<IMAGE_FILE_IRI>}
        # originNode is  TakingPicturesActivity
        ?originImageFile ^user:objectContent ?originNode.
        {
        SELECT ?waveNum ?pathNum ?originNode ?bridgeNode ?targetNode ?score
            WHERE{
                VALUES ?waveNum {  3 }
                VALUES ?pathNum { 1 }
                VALUES?score { 2 }
                VALUES ?secondBridgeNode { UNDEF }
                ?originNode user:withPerson ?bridgeNode.
                ?bridgeNode ^user:withPerson ?targetNode.
                ?targetNode a user:TakingPictures.
                #FILTER (?originNode  != targetNode)
            }
        }
    }
