SELECT DISTINCT ?target {
    ?target a user:TakingPictures .

    # (1) 초기 검색 결과와 동일한 여행 기간 내 찍은 사진만 존재
    FILTER EXISTS {
        VALUES ?origin { <TAKING_PICTURES_IRI> }
        ?travelEngram a user:TravelEngram .
        ?originEventProperty rdfs:subPropertyOf user:event .
        ?travelEngram ?originEventProperty ?origin .
        ?targetEventProperty rdfs:subPropertyOf user:event .
        ?travelEngram ?targetEventProperty ?target .
    }

    # (2) 초기 검색 결과에 포함된 사람이 나온 사진 존재
    FILTER EXISTS {
        ?target user:withPerson ?person .
        VALUES ?origin { <TAKING_PICTURES_IRI> }
        ?origin user:withPerson ?person .
    }
    # (3) 그 외 다른 사람이 나온 사진 없음
    FILTER NOT EXISTS {
        ?target user:withPerson ?person .
        FILTER NOT EXISTS {
            VALUES ?origin { <TAKING_PICTURES_IRI> }
            ?origin user:withPerson ?person .
        }
    }
    # (4) 연관 검색 결과가 초기 검색 결과 외의 사진 보유
    FILTER NOT EXISTS {
        VALUES ?origin { <TAKING_PICTURES_IRI> }
        FILTER (?target = ?origin)
    }
}
