select <OUTPUT>
where{
    ?person rdf:type user:Person .
    VALUES (?person) {<Keywords>}
    BIND("UNDEF" AS ?pivot_score)
    BIND("UNDEF" AS ?pivot_class_score)

    <BODY_GET_TARGET_TRIPLE>
}
<COMPLEX_SORT_METHOD>
