select <OUTPUT>
where{
    <ACTIVITY_FILTER>
    VALUES (?activity) {<Keywords>}
    BIND("UNDEF" AS ?pivot_score)
    BIND("UNDEF" AS ?pivot_class_score)

    <BODY_GET_TARGET_TRIPLE>
}
<COMPLEX_SORT_METHOD>
