SELECT ?activity ?activity_type
WHERE {
    VALUES(?superclass) {(user:Activity) (user:Action)}
    ?class rdfs:subClassOf ?superclass .
    ?activity rdf:type ?class .
    BIND(STRAFTER(STR(?class), str(user:)) as ?activity_type).
}
