#시간(여행) 사람 장소
select distinct ?tp where {
    values ?image {<IMAGE_FILE_IRI>}
    ?tp user:objectContent ?image .
    ?tp rdf:type user:TakingPictures .

    # Travel time filter
    ?tp time:intervalOverlaps|time:intervalIn|time:intervalEquals|time:inside ?travel .
    ?travel rdf:type/rdfs:subClassOf user:TravelEngram .
    ?travel time:hasBeginning/time:inXSDDateTimeStamp ?travel_begin .
    ?travel time:hasEnd/time:inXSDDateTimeStamp ?travel_end .

    FILTER NOT EXISTS{
        ?tp user:atLocation ?tpLocation.
        ?tpLocation a/rdfs:subClassOf ?tpLocationType.
        FILTER(?tpLocationType = location:Home
        || ?tpLocationType = location:WorkPlace
        || ?tpLocationType = location:FrequentlyVisitedPlace)
    }

    # Person filter
    ?tp user:withPerson ?person .

    # Location filter
    ?tp user:atLocation ?location .
}
