SELECT distinct ?s
WHERE {
    ?s rdf:type/rdfs:subClassOf user:SpecialEngram .
    FILTER NOT EXISTS {?s user:event ?something EXPLICIT true. }
    FILTER NOT EXISTS {?s user:specialEvent ?something EXPLICIT true. }
}
